---
- hosts: localhost
  connection: local
  vars:
    dest: "{{ ansible_env.PWD }}/playbooks"
    role: ~
  tasks:
    - name: create directories for roles
      file: >
        path={{ dest }}/roles/{{ role }}/{{ item }}
        state=directory
      when: role != None
      with_items:
        - tasks
        - handlers
        - files
        - templates
        - vars
        - defaults
        - meta

    - name: create files
      file: >
        path={{ dest }}/roles/{{ role }}/{{ item.directory }}/{{ item.file }}
        state=touch
      when: role != None
      with_items:
        - { directory: tasks, file: main.yml }
        - { directory: handlers, file: main.yml }
        - { directory: files, file: empty }
        - { directory: templates, file: empty }
        - { directory: vars, file: main.yml }
        - { directory: defaults, file: main.yml }
        - { directory: meta, file: main.yml }
